//Preparing Gopalganj FIR data for Python

//SET-UP: Basic Definitions

/*CLEAR*/
drop _all       /*all variables and obs are dropped*/
label drop _all /*all defined labels are dropped*/
clear           /*drop _all + label drop _all*/ 
clear mata      /*Mata is a matrix programming language that can be used by those who want to perform matrix calculations interactively and by those who want to add new features to Stata.*/
clear matrix    /*clear all matrices*/

clear all /*or "clear *". Remove all data, value labels, matrices
    scalars, constraints, clusters, stored results, sersets, and Mata functions and objects
    from memory.  They also close all open files and postfiles, clear the class system,
    close any open Graph windows and dialog boxes, drop all programs from memory, and reset
    all timers to zero.*/

/*SETTINGS*/
set more off     /*avoids that stata stops*/ 
set memory 300m  /*sets memory size*/
set matsize 1000 /*sets the maximum number of variables in a model*/
set maxvar 32767 /*maximum number of variables in your dataset*/
set seed 12435   /*initial value of a random number*/

**File Directory

*dibbo -- username for Dibyajyoti.
*For others, please enter your PC Name as username and copy the file path of your DB Desktop. 

if "`c(username)'"=="HP"{
	global dropbox "C:\Users\HP\Dropbox\"
	}
else if "`c(username)'"=="dibbo"{
	global dropbox "C:\Users\dibbo\Dropbox\Debiasing Police in India\005-Data-and-analysis-2022\FIR Data-2024"
	}	
/*enter the main folder for the project in Dropbox as per your system*/	
else if "`c(username)'"=="User3"{
	global dropbox "File-Path"
	}

di "`dropbox'"
	
*File Path
/*enter the local names for the different folders, create the folders if they don't exist*/
global raw "$dropbox\01 raw data"
global do_files "$dropbox\02 do files"
global intermediate_dta "$dropbox\03 intermediate\"
*global tables "$dropbox\03.tables\"
*global graphs "$dropbox\04.graphs\"
global log_files "$dropbox\04 log files\"
global clean_dta "$dropbox\05 clean data\"


* We will log in
capture log close 

log using "${log_files}preparing FIR Data_Gopalganj.log", replace text

* We will add this line from time to time if the program takes time to compute or uses a lot of loops
noisily display as text "The date is " as result "--$S_DATE--" as text " and the time is " as result "--$S_TIME--"

*open the input dta file: baseline_listing_exercise_respondents.dta  "baseline_listing_exercise_respondents.dta"

use "${intermediate_dta}Gopalganj_FIR.dta", clear
split complainant, p(" ")

foreach i of varlist complainant* {
	replace `i' = upper(`i')
	replace `i' = trim(`i')
	replace `i' = itrim(`i')
	replace `i' = "" if `i' == "LATE"
	replace `i' = "" if `i' == "W/O"
	replace `i' = "" if `i' == "S/O"
	replace `i' = "" if `i' == "W/O-"
	replace `i' = "" if `i' == "S/O-"
	replace `i' = "" if `i' == "(SI)"
	replace `i' = "" if `i' == "(ASI)"
	replace `i' = "" if `i' == "(SHO)"
	replace `i' = "" if `i' == "SI"
	replace `i' = "" if `i' == "ASI"
	replace `i' = "" if `i' == "SHO"
	replace `i' = "" if `i' == "S.I."
	replace `i' = "" if `i' == "A.S.I."
	replace `i' = "" if `i' == "S.H.O."
}
drop complainant2-complainant12


* Loop through each string variable
foreach var in complainant1 {
	replace `var' = upper(`var')
	replace `var' = trim(`var')
	replace `var' = itrim(`var')
    * Replace "-" with " "
    replace `var' = subinstr(`var', "-", " ", .)
	* Replace "," with " "
    replace `var' = subinstr(`var', ",", " ", .)
    * Replace "." with " "
    replace `var' = subinstr(`var', ".", " ", .)
	* Replace "(S I)" with " "
	replace `var' = trim(`var')
    replace `var' = subinstr(`var', "(S I)", " ", .)
	* Replace "DR " with " "
	replace `var' = trim(`var')
    replace `var' = subinstr(`var', "DR ", " ", .)
	* Replace "DR. " with " "
    replace `var' = subinstr(`var', "DR. ", " ", .)
	* Replace "0" with " "
    replace `var' = subinstr(`var', "0", " ", .)
	* Replace "1" with " "
    replace `var' = subinstr(`var', "1", " ", .)
	* Replace "2" with " "
    replace `var' = subinstr(`var', "2", " ", .)
	* Replace "3" with " "
    replace `var' = subinstr(`var', "3", " ", .)
	* Replace "4" with " "
    replace `var' = subinstr(`var', "4", " ", .)
	* Replace "5" with " "
    replace `var' = subinstr(`var', "5", " ", .)
	* Replace "6" with " "
    replace `var' = subinstr(`var', "6", " ", .)
	* Replace "7" with " "
    replace `var' = subinstr(`var', "7", " ", .)
	* Replace "8" with " "
    replace `var' = subinstr(`var', "8", " ", .)
	* Replace "9" with " "
    replace `var' = subinstr(`var', "9", " ", .)
	* Replace "(" with " "
    replace `var' = subinstr(`var', "(", " ", .)
	* Replace ")" with " "
    replace `var' = subinstr(`var', ")", " ", .)
	* Replace "/" with " "
    replace `var' = subinstr(`var', "/", " ", .)
	* Replace "\" with " "
    replace `var' = subinstr(`var', "\", " ", .)
	replace `var' = trim(`var')
}

replace complainant1 = "" if complainant1 == "S I"
replace complainant1 = "" if complainant1 == "S S B"
replace complainant1 = "" if complainant1 == "P T C"
replace complainant1 = "" if complainant1 == "B D O"
replace complainant1 = "" if complainant1 == "B H G"
replace complainant1 = "" if complainant1 == "BHG"
replace complainant1 = "" if complainant1 == "J P"
replace complainant1 = "" if complainant1 == "K H"
replace complainant1 = "" if complainant1 == "K N"
replace complainant1 = "" if complainant1 == "VILL MADHUBANI"
replace complainant1 = "" if complainant1 == "VILL DAINMARVA"
replace complainant1 = "" if complainant1 == "MS"
replace complainant1 = "" if complainant1 == "PTC"
replace complainant1 = "" if complainant1 == "SII"
replace complainant1 = "" if complainant1 == "S I"
replace complainant1 = "" if complainant1 == "A S I"
replace complainant1 = "" if complainant1 == "S H O"
replace complainant1 = "" if complainant1 == "S  H O"
replace complainant1 = "" if complainant1 == "P S I"
replace complainant1 = "" if complainant1 == "K S H"
replace complainant1 = "" if complainant1 == "D I G"
replace complainant1 = "" if complainant1 == "U I D"
replace complainant1 = "" if complainant1 == "D I G"
replace complainant1 = "" if complainant1 == "JAMMU"
replace complainant1 = "" if complainant1 == "V P S"
replace complainant1 = "" if complainant1 == "AST DPT INS"
replace complainant1 = "" if complainant1 == "A S I G D"
replace complainant1 = "" if complainant1 == "HC GD SSB"
replace complainant1 = "" if complainant1 == "P P K"
replace complainant1 = "RANA" if complainant1 == "S I RAN"

replace complainant1 = "SHIVAM" if complainant1 == "SHIVAM SANU"
replace complainant1 = "AJAY" if complainant1 == "अजय"
replace complainant1 = "RAJEEV" if complainant1 == "राजीव"
replace complainant1 = "SUKHAL" if complainant1 == "सुखल"

drop complainant13 complainant14
split complainant1, p(" ")
replace complainant1 = "MOHAMMAD" if complainant11 == "MD"
replace complainant1 = "MOHAMMAD" if complainant1 == "M D"
*drop complainant11 complainant12

drop complainant
rename complainant1 complainant
*gen complainant1 = substr(complainant,-4,.)
*drop if complainant1 == ""
*keep complainant1
replace complainant = complainant11 if complainant == "" & complainant11 != "" & strlen(complainant11) > 3
replace complainant = complainant12 if complainant == "" & complainant12 != "" & complainant11 != "" & strlen(complainant12) > 3
replace complainant = complainant13 if complainant == "" & complainant13 != "" & complainant12 != "" & complainant11 != "" & strlen(complainant13) > 3
replace complainant = complainant14 if complainant == "" &  complainant14 != "" & complainant13 != "" & complainant12 != "" & complainant11 != "" & strlen(complainant14) > 3
replace complainant = proper(complainant)
replace complainant = "" if complainant == "A S I Gd"
replace complainant = "" if complainant == "Ssb"
replace complainant = "" if complainant == "Psi"
replace complainant = "" if complainant == "C I"
replace complainant = "" if complainant == "P I"
replace complainant = "" if complainant == "Dr"
replace complainant = "" if complainant == "Smt"
replace complainant = "" if complainant == "Sri"
replace complainant = "" if complainant == "Son"
replace complainant = "" if complainant == "Dr"
replace complainant = "" if complainant == "A N"
replace complainant = "" if complainant == "A S"
replace complainant = "" if complainant == "A Si"
replace complainant = "" if complainant == "Aaa"
replace complainant = "" if complainant == "Aaaaaa"
replace complainant = "" if complainant == "Aaaaaaa"
replace complainant = "" if complainant == "Aas"
replace complainant = "" if complainant == "Aai"
replace complainant = "" if complainant == "Aash"
replace complainant = "" if complainant == "Abi"
replace complainant = "" if complainant == "Aeil"
replace complainant = "" if complainant == "Aji"
replace complainant = "" if complainant == "Ajy"
replace complainant = "" if complainant == "Ale"
replace complainant = "" if complainant == "Ara"
replace complainant = "" if complainant == "Ash"
replace complainant = "" if complainant == "Aso"
replace complainant = "" if complainant == "Att"
replace complainant = "" if complainant == "Avi"
replace complainant = "" if complainant == "B L"
replace complainant = "" if complainant == "Dig"
replace complainant = "" if complainant == "Dos"
replace complainant = "" if complainant == "Dri"
replace complainant = "" if complainant == "Ema"
replace complainant = "" if complainant == "Ful"
replace complainant = "" if complainant == "Gkj"
replace complainant = "" if complainant == "Ida"
replace complainant = "" if complainant == "Idu"
replace complainant = "" if complainant == "Ish"
replace complainant = "" if complainant == "Jjl"
replace complainant = "" if complainant == "Jki"
replace complainant = "" if complainant == "Jta"
replace complainant = "" if complainant == "Kjl"
replace complainant = "" if complainant == "Kkk"
replace complainant = "" if complainant == "Kkl"
replace complainant = "" if complainant == "Kll"
replace complainant = "" if complainant == "Lll"
replace complainant = "" if complainant == "Mad"
replace complainant = "" if complainant == "Mis"
replace complainant = "" if complainant == "Mrs"
replace complainant = "" if complainant == "N N"
replace complainant = "" if complainant == "Nav"
replace complainant = "" if complainant == "Nbi"
replace complainant = "" if complainant == "Nek"
replace complainant = "" if complainant == "Oli"
replace complainant = "" if complainant == "Pna"
replace complainant = "" if complainant == "Ppk"
replace complainant = "" if complainant == "R S"
replace complainant = "" if complainant == "Ran"
replace complainant = "" if complainant == "Rav"
replace complainant = "" if complainant == "Raw"
replace complainant = "" if complainant == "Rit"
replace complainant = "" if complainant == "Rup"
replace complainant = "" if complainant == "Sah"
replace complainant = "" if complainant == "Sal"
replace complainant = "" if complainant == "Sha"
replace complainant = "" if complainant == "Sit"
replace complainant = "" if complainant == "Skh"
replace complainant = "" if complainant == "Sub"
replace complainant = "" if complainant == "Tun"
replace complainant = "" if complainant == "Uid"
replace complainant = "" if complainant == "Uin"
replace complainant = "" if complainant == "Ume"
replace complainant = "" if complainant == "Anadnd"
replace complainant = "Anjali" if complainant == "Anajli"
replace complainant = "Anjali" if complainant == "Anjal"
replace complainant = "Laxmi" if complainant == "Axmi"
replace complainant = "" if complainant == "College"
replace complainant = "" if complainant == "Constable"
replace complainant = "" if complainant == "Excutive"
replace complainant = "" if complainant == "Mu Aa"
replace complainant = "" if complainant == "Mu Bacchi"
replace complainant = "" if complainant == "Mu Gaudi"
replace complainant = "" if complainant == "Muaali"
replace complainant = "" if complainant == "P Si"
replace complainant = "" if complainant == "Prabhari"
replace complainant = "Arpita" if complainant == "Rapita"
replace complainant = "" if complainant == "Shiya"
replace complainant = "" if complainant == "Shlma"
replace complainant = "" if complainant == "Shmabhu"
replace complainant = "" if complainant == "Shri"
replace complainant = "" if complainant == "Sree"
replace complainant = "" if complainant == "Trainee"
replace complainant = "" if complainant == "Videshi"
replace complainant = "" if complainant == "Vigilance"
replace complainant = "" if complainant == "Husbadi"
replace complainant = "" if complainant == "Iandu"
replace complainant = "" if complainant == "Ilachaei"
replace complainant = "" if complainant == "Iliye"
replace complainant = "" if complainant == "Xxxxxx"
replace complainant = "" if complainant == "Xxxx"
replace complainant = "" if complainant == "Ssaheb"
replace complainant = "" if complainant == "Victim"
replace complainant = "" if complainant == "Si Gd"
replace complainant = "" if complainant == "Asisstant"
replace complainant = "" if complainant == "Asst"
replace complainant = "" if complainant == "Colector"
replace complainant = "" if complainant == "Congres"
replace complainant = "" if complainant == "Congress"
replace complainant = "" if complainant == "Deupty" 
replace complainant = "" if complainant == "Full"
replace complainant = "" if complainant == "Chaukidar"
replace complainant = "" if complainant == "Chaukeedar"
replace complainant = "" if complainant == "Chaukida"
replace complainant = "" if complainant == "Chaukidar"
replace complainant = "" if complainant == "Chaukidar"
replace complainant = "" if complainant == "Chaukidar"
replace complainant = "" if complainant == "Bgh"
replace complainant = "" if complainant == "Ugi"
replace complainant = "" if complainant == "Ban"
replace complainant = "" if complainant == "Choukidar"
replace complainant = "" if complainant == "Chowkidar"
replace complainant = "" if complainant == "Chukidar"
replace complainant = "" if complainant == "Cowkidar"
replace complainant = "" if complainant == "A C"
replace complainant = "" if complainant == "Ami"
replace complainant = "" if complainant == "Ase"
replace complainant = "" if complainant == "Asi"
replace complainant = "" if complainant == "B K"
replace complainant = "" if complainant == "Ayi"
replace complainant = "" if complainant == "Ati"
replace complainant = "" if complainant == "Bdo"
replace complainant = "" if complainant == "Bhu"
replace complainant = "" if complainant == "C O"
replace complainant = "" if complainant == "C S"
replace complainant = "" if complainant == "Cho"
replace complainant = "" if complainant == "Dya"
replace complainant = "" if complainant == "Ins"
replace complainant = "" if complainant == "Jaz"
replace complainant = "" if complainant == "Jez"
replace complainant = "" if complainant == "Law"
replace complainant = "" if complainant == "Mit"
replace complainant = "Mohammad" if complainant == "Moh"
replace complainant = "" if complainant == "N B"
replace complainant = "" if complainant == "Pad"
replace complainant = "" if complainant == "Pan"
replace complainant = "" if complainant == "Pro"
replace complainant = "" if complainant == "Rja"
replace complainant = "" if complainant == "Rui"
replace complainant = "" if complainant == "Sir"
replace complainant = "" if complainant == "V K"
replace complainant = "" if complainant == "Wed"
replace complainant = "" if complainant == "Home" 
replace complainant = "" if complainant == "Ins Cum Sho" 
replace complainant = "Mahendra" if complainant == "S I  Mahendra" 
replace complainant = "" if complainant == "Sho Si"
replace complainant = "" if complainant == "Si Com Sho"
replace complainant = "" if complainant == "Si Sho"
replace complainant = "" if complainant == "Cahukidar"
replace complainant = "" if complainant == "Chakidar"
replace complainant = "" if complainant == "Chaokidar"
replace complainant = "" if complainant == "Chokidar"
replace complainant = "" if complainant == "Chowidar"
replace complainant = "" if complainant == "Chsukidar"
replace complainant = "" if complainant == "Havaldar"
replace complainant = "" if complainant == "Hawaldar"
replace complainant = "" if complainant == "Awd"
replace complainant = "" if complainant == "B N"
replace complainant = "" if complainant == "B P"
replace complainant = "" if complainant == "Chu"
replace complainant = "" if complainant == "Bol"
replace complainant = "" if complainant == "D P"
replace complainant = "" if complainant == "D R"
replace complainant = "" if complainant == "Dhi"
replace complainant = "" if complainant == "Doc"
replace complainant = "" if complainant == "Dpc"
replace complainant = "" if complainant == "Hav"
replace complainant = "" if complainant == "Etu"
replace complainant = "" if complainant == "J E"
replace complainant = "" if complainant == "Jaj"
replace complainant = "" if complainant == "Kis"
replace complainant = "" if complainant == "Kuj"
replace complainant = "" if complainant == "Kum"
replace complainant = "" if complainant == "Lki"
replace complainant = "" if complainant == "M O"
replace complainant = "" if complainant == "M S"
replace complainant = "" if complainant == "Mna"
replace complainant = "" if complainant == "Mus"
replace complainant = "" if complainant == "S G"
replace complainant = "" if complainant == "Sap"
replace complainant = "" if complainant == "Sif"
replace complainant = "" if complainant == "Ush"
replace complainant = "" if complainant == "Vis"
replace complainant = "" if complainant == "Yad"
replace complainant = "" if complainant == "Yay" 
replace complainant = "" if complainant == "Consable"
replace complainant = "" if complainant == "Chaikidar" 
replace complainant = "" if complainant == "Hawldar" 
replace complainant = "" if complainant == "Tasildar"

*replace complainant = complainant15 if complainant15 != "" & complainant14 != "" & complainant13 != "" & complainant12 != "" & complainant11 != "" & strlen(complainant14) > 3
replace complainant = subinstr(complainant, "ndre", "ndra", .)
drop if strlen(complainant) <= 2
drop complainant11-complainant14
save "${intermediate_dta}Clean_Python\gopalganj.dta", replace

*macro set intermediate_dta "C:\Users\dibbo\Dropbox\Debiasing Police in India\005-Data-and-analysis-2022\FIR Data-2024\03 intermediate"

. python

import os
import pandas as pd
from guess_indian_gender import IndianGenderPredictor

# Load the .dta file using Pandas
df = pd.read_stata('C:\\Users\\dibbo\\Dropbox\\Debiasing Police in India\\005-Data-and-analysis-2022\\FIR Data-2024\\03 intermediate\\Clean_Python\\gopalganj.dta')

# Create an instance of IndianGenderPredictor
igp = IndianGenderPredictor()

def predict_gender(complainant):
    # Truncate the string to the last 8 characters
    complainant_truncated = complainant[-4:]
    
    # Predict gender using the truncated string
    gender = igp.predict(name=complainant_truncated)
    
    return 1 if gender == 'male' else 0

# Create a new column 'gender_dummy' based on the 'complainant' variable
df['gender_dummy'] = df['complainant'].apply(predict_gender)

# Convert 'firdate' column to strings and handle null values
df['firdate'] = df['firdate'].astype(str)

# Encode the DataFrame columns with non-ASCII characters
df_encoded = df.map(lambda x: x.encode('utf-8').decode('latin-1') if isinstance(x, str) else x)

# Construct the file path
output_file_path = os.path.join('C:\\Users\\dibbo\\Dropbox\\Debiasing Police in India\\005-Data-and-analysis-2022\\FIR Data-2024\\03 intermediate\\Clean_Python\\modified_gopalganj.dta')

# Write the encoded DataFrame to the specified file path
df_encoded.to_stata(output_file_path, version=117)

end


use "${intermediate_dta}Clean_Python\modified_gopalganj.dta", clear
*drop complainant13 complainant14

gen last_letter = substr(complainant, -1, 1)
gen vowel_dummy = 0
replace vowel_dummy = 1 if last_letter == "a" | last_letter == "e" | last_letter == "i" | last_letter == "o" | last_letter == "u"

replace vowel_dummy = 1 if last_letter == "a" | last_letter == "e" | last_letter == "i" | last_letter == "o" | last_letter == "u"
replace gender_dummy = 0 if complainant == "Abha"
replace gender_dummy = 0 if complainant == "Alka"
replace gender_dummy = 0 if complainant == "Ambika"
replace gender_dummy = 0 if complainant == "Angira"
replace gender_dummy = 0 if complainant == "Asha"
replace gender_dummy = 0 if complainant == "Asiya"
replace gender_dummy = 0 if complainant == "Asma"
replace gender_dummy = 0 if complainant == "Bina"
replace gender_dummy = 0 if complainant == "Binda"
replace gender_dummy = 0 if complainant == "Brindra"
replace gender_dummy = 0 if complainant == "Giraja"
replace gender_dummy = 0 if complainant == "Gita"
replace gender_dummy = 0 if complainant == "Hamida"
replace gender_dummy = 0 if complainant == "Hasneara"
replace gender_dummy = 0 if complainant == "Hema"
replace gender_dummy = 0 if complainant == "Hina"
replace gender_dummy = 0 if complainant == "Hira"
replace gender_dummy = 0 if complainant == "Husanara"
replace gender_dummy = 0 if complainant == "Husnara"
replace gender_dummy = 0 if complainant == "Jahanara"
replace gender_dummy = 0 if complainant == "Jaya"
replace gender_dummy = 0 if complainant == "Jira"
replace gender_dummy = 0 if complainant == "Mala"
replace gender_dummy = 0 if complainant == "Maya"
replace gender_dummy = 0 if complainant == "Medha"
replace gender_dummy = 0 if complainant == "Menka"
replace gender_dummy = 0 if complainant == "Mina"
replace gender_dummy = 0 if complainant == "Mira"
replace gender_dummy = 0 if complainant == "Mona"
replace gender_dummy = 0 if complainant == "Neha"
replace gender_dummy = 0 if complainant == "Nipa"
replace gender_dummy = 0 if complainant == "Nita"
replace gender_dummy = 0 if complainant == "Prarthana"
replace gender_dummy = 0 if complainant == "Prarthna"
replace gender_dummy = 0 if complainant == "Prativa"
replace gender_dummy = 0 if complainant == "Puja"
replace gender_dummy = 0 if complainant == "Rabeya"
replace gender_dummy = 0 if complainant == "Rafeya"
replace gender_dummy = 0 if complainant == "Rambha"
replace gender_dummy = 0 if complainant == "Ratna"
replace gender_dummy = 0 if complainant == "Resma"
replace gender_dummy = 0 if complainant == "Rima"
replace gender_dummy = 0 if complainant == "Rina"
replace gender_dummy = 0 if complainant == "Rita"
replace gender_dummy = 0 if complainant == "Ruma"
replace gender_dummy = 0 if complainant == "Runa"
replace gender_dummy = 0 if complainant == "Rupa"
replace gender_dummy = 0 if complainant == "Saba"
replace gender_dummy = 0 if complainant == "Safina"
replace gender_dummy = 0 if complainant == "Saiyra"
replace gender_dummy = 0 if complainant == "Sajda"
replace gender_dummy = 0 if complainant == "Sama"
replace gender_dummy = 0 if complainant == "Sandhiya"
replace gender_dummy = 0 if complainant == "Sardha"
replace gender_dummy = 0 if complainant == "Shardha"
replace gender_dummy = 0 if complainant == "Shashikala"
replace gender_dummy = 0 if complainant == "Sima"
replace gender_dummy = 0 if complainant == "Sita"
replace gender_dummy = 0 if complainant == "Sona"
replace gender_dummy = 0 if complainant == "Sumedha"
replace gender_dummy = 0 if complainant == "Tamanna"
replace gender_dummy = 0 if complainant == "Tara"
replace gender_dummy = 0 if complainant == "Uma"
replace gender_dummy = 0 if complainant == "Umma"
replace gender_dummy = 0 if complainant == "Usha"
replace gender_dummy = 0 if complainant == "Vinda"
replace gender_dummy = 0 if complainant == "Aamana"
replace gender_dummy = 0 if complainant == "Aashya"
replace gender_dummy = 0 if complainant == "Aasiya"
replace gender_dummy = 0 if complainant == "Abdula"
replace gender_dummy = 0 if complainant == "Adeya"
replace gender_dummy = 0 if complainant == "Adhiya"
replace gender_dummy = 0 if complainant == "Adya"
replace gender_dummy = 0 if complainant == "Ahilya"
replace gender_dummy = 0 if complainant == "Aisa"
replace gender_dummy = 0 if complainant == "Anu"
replace gender_dummy = 0 if complainant == "Ajita"
replace gender_dummy = 0 if complainant == "Ajma"
replace gender_dummy = 0 if complainant == "Ajmara"
replace gender_dummy = 0 if complainant == "Ajmeyaara"
replace gender_dummy = 0 if complainant == "Alamara"
replace gender_dummy = 0 if complainant == "Almara"
replace gender_dummy = 0 if complainant == "Almeara"
replace gender_dummy = 0 if complainant == "Anandi"
replace gender_dummy = 0 if complainant == "Anjamra"
replace gender_dummy = 0 if complainant == "Anju"
replace gender_dummy = 0 if complainant == "Anjuma"
replace gender_dummy = 0 if complainant == "Anula"
replace gender_dummy = 0 if complainant == "Apasari"
replace gender_dummy = 0 if complainant == "Areya"
replace gender_dummy = 0 if complainant == "Arfa"
replace gender_dummy = 0 if complainant == "Arti"
replace gender_dummy = 0 if complainant == "Arundhati"
replace gender_dummy = 0 if complainant == "Ashiya"
replace gender_dummy = 0 if complainant == "Ashu"
replace gender_dummy = 0 if complainant == "Asvini"
replace gender_dummy = 0 if complainant == "Asyana"
replace gender_dummy = 0 if complainant == "Atifa"
replace gender_dummy = 0 if complainant == "Ayasa"
replace gender_dummy = 0 if complainant == "Ayesa"
replace gender_dummy = 0 if complainant == "Aysa"
replace gender_dummy = 0 if complainant == "Bigni"
replace gender_dummy = 0 if complainant == "Bijli"
replace gender_dummy = 0 if complainant == "Bindeshawari"
replace gender_dummy = 0 if complainant == "Bindeshwari"
replace gender_dummy = 0 if complainant == "Bindeswari"
replace gender_dummy = 0 if complainant == "Bindi"
replace gender_dummy = 0 if complainant == "Boli"
replace gender_dummy = 0 if complainant == "Budhiya"
replace gender_dummy = 0 if complainant == "Candrauti"
replace gender_dummy = 0 if complainant == "Chabilla"
replace gender_dummy = 0 if complainant == "Chandasi"
replace gender_dummy = 0 if complainant == "Chandrabati"
replace gender_dummy = 0 if complainant == "Chandrabati"
replace gender_dummy = 0 if complainant == "Daraupadi"
replace gender_dummy = 0 if complainant == "Daropadi"
replace gender_dummy = 0 if complainant == "Dashiya"
replace gender_dummy = 0 if complainant == "Devaki"
replace gender_dummy = 0 if complainant == "Devi"
replace gender_dummy = 0 if complainant == "Devndi"
replace gender_dummy = 0 if complainant == "Devrasi"
replace gender_dummy = 0 if complainant == "Dimpi"
replace gender_dummy = 0 if complainant == "Dipa"
replace gender_dummy = 0 if complainant == "Divye"
replace gender_dummy = 0 if complainant == "Dropadi"
replace gender_dummy = 0 if complainant == "Durgawti"
replace gender_dummy = 0 if complainant == "Fija"
replace gender_dummy = 0 if complainant == "Fijja"
replace gender_dummy = 0 if complainant == "Fuleshwari"
replace gender_dummy = 0 if complainant == "Fuleswari"
replace gender_dummy = 0 if complainant == "Fuljhari"
replace gender_dummy = 0 if complainant == "Funilla"
replace gender_dummy = 0 if complainant == "Fulgeni"
replace gender_dummy = 0 if complainant == "Fuleni"
replace gender_dummy = 0 if complainant == "Gajintri"
replace gender_dummy = 0 if complainant == "Gajintri"
replace gender_dummy = 0 if complainant == "Gayati"
replace gender_dummy = 0 if complainant == "Gayetri"
replace gender_dummy = 0 if complainant == "Gaynti"
replace gender_dummy = 0 if complainant == "Geerja"
replace gender_dummy = 0 if complainant == "Gendauli"
replace gender_dummy = 0 if complainant == "Godavri"
replace gender_dummy = 0 if complainant == "Gendawali"
replace gender_dummy = 0 if complainant == "Gireja"
replace gender_dummy = 0 if complainant == "Godawali"
replace gender_dummy = 0 if complainant == "Godawri"
replace gender_dummy = 0 if complainant == "Gokhula"
replace gender_dummy = 0 if complainant == "Godawari"
replace gender_dummy = 0 if complainant == "Gulabi"
replace gender_dummy = 0 if complainant == "Gulnara"
replace gender_dummy = 0 if complainant == "Gulneyra"
replace gender_dummy = 0 if complainant == "Gulsaba"
replace gender_dummy = 0 if complainant == "Gulsabba"
replace gender_dummy = 0 if complainant == "Gunja"
replace gender_dummy = 0 if complainant == "Hena"
replace gender_dummy = 0 if complainant == "Hibja"
replace gender_dummy = 0 if complainant == "Hirabati"
replace gender_dummy = 0 if complainant == "Hirajhari"
replace gender_dummy = 0 if complainant == "Husniyara"
replace gender_dummy = 0 if complainant == "Hussainara"
replace gender_dummy = 0 if complainant == "Indira"
replace gender_dummy = 0 if complainant == "Indu"
replace gender_dummy = 0 if complainant == "Isha"
replace gender_dummy = 0 if complainant == "Ishu"
replace gender_dummy = 0 if complainant == "Jagali"
replace gender_dummy = 0 if complainant == "Jahara"
replace gender_dummy = 0 if complainant == "Jaheda"
replace gender_dummy = 0 if complainant == "Jahnaura"
replace gender_dummy = 0 if complainant == "Jahra"
replace gender_dummy = 0 if complainant == "Jakiya"
replace gender_dummy = 0 if complainant == "Jamaleara"
replace gender_dummy = 0 if complainant == "Janaki"
replace gender_dummy = 0 if complainant == "Jankiya"
replace gender_dummy = 0 if complainant == "Janwari"
replace gender_dummy = 0 if complainant == "Japhara"
replace gender_dummy = 0 if complainant == "Jarouna"
replace gender_dummy = 0 if complainant == "Jasiya"
replace gender_dummy = 0 if complainant == "Jayantri"
replace gender_dummy = 0 if complainant == "Jayila"
replace gender_dummy = 0 if complainant == "Jeba"
replace gender_dummy = 0 if complainant == "Jeva"
replace gender_dummy = 0 if complainant == "Jeya"
replace gender_dummy = 0 if complainant == "Jhanara"
replace gender_dummy = 0 if complainant == "Jhumka"
replace gender_dummy = 0 if complainant == "Jiuti"
replace gender_dummy = 0 if complainant == "Jiya"
replace gender_dummy = 0 if complainant == "Jiyani"
replace gender_dummy = 0 if complainant == "Johara"
replace gender_dummy = 0 if complainant == "Jolaisa"
replace gender_dummy = 0 if complainant == "Jonahiya"
replace gender_dummy = 0 if complainant == "Jugneyara"
replace gender_dummy = 0 if complainant == "Juhi"
replace gender_dummy = 0 if complainant == "Jyota"
replace gender_dummy = 0 if complainant == "Kamya"
replace gender_dummy = 0 if complainant == "Kaudhilya"
replace gender_dummy = 0 if complainant == "Kausailya"
replace gender_dummy = 0 if complainant == "Kaushari"
replace gender_dummy = 0 if complainant == "Kaushyala"
replace gender_dummy = 0 if complainant == "Kavila"
replace gender_dummy = 0 if complainant == "Khairula"
replace gender_dummy = 0 if complainant == "Khalida"
replace gender_dummy = 0 if complainant == "Khursheda"
replace gender_dummy = 0 if complainant == "Khusabu"
replace gender_dummy = 0 if complainant == "Khusabu"
replace gender_dummy = 0 if complainant == "Khushbuda"
replace gender_dummy = 0 if complainant == "Khushnama"
replace gender_dummy = 0 if complainant == "Khushnema"
replace gender_dummy = 0 if complainant == "Kimeya"
replace gender_dummy = 0 if complainant == "Kimi"
replace gender_dummy = 0 if complainant == "Kisori"
replace gender_dummy = 0 if complainant == "Kopila"
replace gender_dummy = 0 if complainant == "Kotila"
replace gender_dummy = 0 if complainant == "Ladli"
replace gender_dummy = 0 if complainant == "Lakki"
replace gender_dummy = 0 if complainant == "Lakshmiya"
replace gender_dummy = 0 if complainant == "Lali"
replace gender_dummy = 0 if complainant == "Lata"
replace gender_dummy = 0 if complainant == "Lilabati"
replace gender_dummy = 0 if complainant == "Lilawti"
replace gender_dummy = 0 if complainant == "Mahanthi"
replace gender_dummy = 0 if complainant == "Maheshwri"
replace gender_dummy = 0 if complainant == "Malati"
replace gender_dummy = 0 if complainant == "Manirka"
replace gender_dummy = 0 if complainant == "Medhu"
replace gender_dummy = 0 if complainant == "Mega"
replace gender_dummy = 0 if complainant == "Mili"
replace gender_dummy = 0 if complainant == "Minti"
replace gender_dummy = 0 if complainant == "Misi"
replace gender_dummy = 0 if complainant == "Monaka"
replace gender_dummy = 0 if complainant == "Monaki"
replace gender_dummy = 0 if complainant == "Moni"
replace gender_dummy = 0 if complainant == "Mridula"
replace gender_dummy = 0 if complainant == "Mukta"
replace gender_dummy = 0 if complainant == "Muskiya"
replace gender_dummy = 0 if complainant == "Mutuja"
replace gender_dummy = 0 if complainant == "Nadira"
replace gender_dummy = 0 if complainant == "Naema"
replace gender_dummy = 0 if complainant == "Nagama"
replace gender_dummy = 0 if complainant == "Nagesari"
replace gender_dummy = 0 if complainant == "Nagima"
replace gender_dummy = 0 if complainant == "Naiyma"
replace gender_dummy = 0 if complainant == "Najama"
replace gender_dummy = 0 if complainant == "Najara"
replace gender_dummy = 0 if complainant == "Najare"
replace gender_dummy = 0 if complainant == "Namiya"
replace gender_dummy = 0 if complainant == "Nanaki"
replace gender_dummy = 0 if complainant == "Nasira"
replace gender_dummy = 0 if complainant == "Nasiya"
replace gender_dummy = 0 if complainant == "Niki"
replace gender_dummy = 0 if complainant == "Nira"
replace gender_dummy = 0 if complainant == "Nisa"
replace gender_dummy = 0 if complainant == "Nishi"
replace gender_dummy = 0 if complainant == "Nishu"
replace gender_dummy = 0 if complainant == "Niti"
replace gender_dummy = 0 if complainant == "Nitu"
replace gender_dummy = 0 if complainant == "Njara"
replace gender_dummy = 0 if complainant == "Noornama"
replace gender_dummy = 0 if complainant == "Noorswa"
replace gender_dummy = 0 if complainant == "Nurali"
replace gender_dummy = 0 if complainant == "Nurjha"
replace gender_dummy = 0 if complainant == "Nurnama"
replace gender_dummy = 0 if complainant == "Nurneja"
replace gender_dummy = 0 if complainant == "Nurnesa"
replace gender_dummy = 0 if complainant == "Nursawa"
replace gender_dummy = 0 if complainant == "Nurujama"
replace gender_dummy = 0 if complainant == "Oshi"
replace gender_dummy = 0 if complainant == "Pallawi"
replace gender_dummy = 0 if complainant == "Pammi"
replace gender_dummy = 0 if complainant == "Parwti"
replace gender_dummy = 0 if complainant == "Phiroja"
replace gender_dummy = 0 if complainant == "Phooljhari"
replace gender_dummy = 0 if complainant == "Phuleni"
replace gender_dummy = 0 if complainant == "Phuljhadi"
replace gender_dummy = 0 if complainant == "Phuljhari"
replace gender_dummy = 0 if complainant == "Phulkeshi"
replace gender_dummy = 0 if complainant == "Phulsara"
replace gender_dummy = 0 if complainant == "Piyaunshu"
replace gender_dummy = 0 if complainant == "Prabhawari"
replace gender_dummy = 0 if complainant == "Prabhawti"
replace gender_dummy = 0 if complainant == "Pragati"
replace gender_dummy = 0 if complainant == "Priyanshu"
replace gender_dummy = 0 if complainant == "Punjita"
replace gender_dummy = 0 if complainant == "Puni"
replace gender_dummy = 0 if complainant == "Punya"
replace gender_dummy = 0 if complainant == "Pushapa"
replace gender_dummy = 0 if complainant == "Rabadi"
replace gender_dummy = 0 if complainant == "Rabari"
replace gender_dummy = 0 if complainant == "Rabdi"
replace gender_dummy = 0 if complainant == "Rabri"
replace gender_dummy = 0 if complainant == "Rabya"
replace gender_dummy = 0 if complainant == "Raji"
replace gender_dummy = 0 if complainant == "Rajwali"
replace gender_dummy = 0 if complainant == "Rakeya"
replace gender_dummy = 0 if complainant == "Rakiba"
replace gender_dummy = 0 if complainant == "Rakima"
replace gender_dummy = 0 if complainant == "Ramawti"
replace gender_dummy = 0 if complainant == "Ramya"
replace gender_dummy = 0 if complainant == "Rangna"
replace gender_dummy = 0 if complainant == "Ranjita"
replace gender_dummy = 0 if complainant == "Ranu"
replace gender_dummy = 0 if complainant == "Raya"
replace gender_dummy = 0 if complainant == "Rebha"
replace gender_dummy = 0 if complainant == "Reja"
replace gender_dummy = 0 if complainant == "Reji"
replace gender_dummy = 0 if complainant == "Rema"
replace gender_dummy = 0 if complainant == "Remi"
replace gender_dummy = 0 if complainant == "Rena"
replace gender_dummy = 0 if complainant == "Renu"
replace gender_dummy = 0 if complainant == "Reshami"
replace gender_dummy = 0 if complainant == "Reshu"
replace gender_dummy = 0 if complainant == "Resmi"
replace gender_dummy = 0 if complainant == "Rifa"
replace gender_dummy = 0 if complainant == "Rini"
replace gender_dummy = 0 if complainant == "Rishu"
replace gender_dummy = 0 if complainant == "Risu"
replace gender_dummy = 0 if complainant == "Ritu"
replace gender_dummy = 0 if complainant == "Riya"
replace gender_dummy = 0 if complainant == "Rmauti"
replace gender_dummy = 0 if complainant == "Roji"
replace gender_dummy = 0 if complainant == "Rokya"
replace gender_dummy = 0 if complainant == "Ruba"
replace gender_dummy = 0 if complainant == "Rubi"
replace gender_dummy = 0 if complainant == "Rubiyana"
replace gender_dummy = 0 if complainant == "Rucchi"
replace gender_dummy = 0 if complainant == "Ruhe"
replace gender_dummy = 0 if complainant == "Ruhi"
replace gender_dummy = 0 if complainant == "Rukaeya"
replace gender_dummy = 0 if complainant == "Rukhiya"
replace gender_dummy = 0 if complainant == "Rukma"
replace gender_dummy = 0 if complainant == "Rumana"
replace gender_dummy = 0 if complainant == "Sabeya"
replace gender_dummy = 0 if complainant == "Sabiha"
replace gender_dummy = 0 if complainant == "Sabira"
replace gender_dummy = 0 if complainant == "Sabrunnesa"
replace gender_dummy = 0 if complainant == "Safaya"
replace gender_dummy = 0 if complainant == "Safeya"
replace gender_dummy = 0 if complainant == "Safiyana"
replace gender_dummy = 0 if complainant == "Sagira"
replace gender_dummy = 0 if complainant == "Sahnara"
replace gender_dummy = 0 if complainant == "Sairula"
replace gender_dummy = 0 if complainant == "Salama"
replace gender_dummy = 0 if complainant == "Salamu"
replace gender_dummy = 0 if complainant == "Saleha"
replace gender_dummy = 0 if complainant == "Saleya"
replace gender_dummy = 0 if complainant == "Salha"
replace gender_dummy = 0 if complainant == "Sambeya"
replace gender_dummy = 0 if complainant == "Samida"
replace gender_dummy = 0 if complainant == "Sandheya"
replace gender_dummy = 0 if complainant == "Sangida"
replace gender_dummy = 0 if complainant == "Sanila" 
replace gender_dummy = 0 if complainant == "Sanjha"
replace gender_dummy = 0 if complainant == "Sanji"
replace gender_dummy = 0 if complainant == "Sanjita"
replace gender_dummy = 0 if complainant == "Sarada"
replace gender_dummy = 0 if complainant == "Sarali"
replace gender_dummy = 0 if complainant == "Sarli"
replace gender_dummy = 0 if complainant == "Sarsawti"
replace gender_dummy = 0 if complainant == "Savila"
replace gender_dummy = 0 if complainant == "Saweya"
replace gender_dummy = 0 if complainant == "Sayara"
replace gender_dummy = 0 if complainant == "Sayda"
replace gender_dummy = 0 if complainant == "Sehra"
replace gender_dummy = 0 if complainant == "Sharada"
replace gender_dummy = 0 if complainant == "Sheila"
replace gender_dummy = 0 if complainant == "Shyara"
replace gender_dummy = 0 if complainant == "Simayati"
replace gender_dummy = 0 if complainant == "Siyalati"
replace gender_dummy = 0 if complainant == "Slma"
replace gender_dummy = 0 if complainant == "Sofhiya"
replace gender_dummy = 0 if complainant == "Soni"
replace gender_dummy = 0 if complainant == "Subasani"
replace gender_dummy = 0 if complainant == "Subasni"
replace gender_dummy = 0 if complainant == "Subhasani"
replace gender_dummy = 0 if complainant == "Subhsani"
replace gender_dummy = 0 if complainant == "Sughandhi"
replace gender_dummy = 0 if complainant == "Sughandi"
replace gender_dummy = 0 if complainant == "Sugiya"
replace gender_dummy = 0 if complainant == "Suja"
replace gender_dummy = 0 if complainant == "Sujita"
replace gender_dummy = 0 if complainant == "Sujra"
replace gender_dummy = 0 if complainant == "Sukavari"
replace gender_dummy = 0 if complainant == "Sukeshwari"
replace gender_dummy = 0 if complainant == "Sumutra"
replace gender_dummy = 0 if complainant == "Sunaia"
replace gender_dummy = 0 if complainant == "Sunari"
replace gender_dummy = 0 if complainant == "Sunila"
replace gender_dummy = 0 if complainant == "Surabhi"
replace gender_dummy = 0 if complainant == "Sursati"
replace gender_dummy = 0 if complainant == "Sushiya"
replace gender_dummy = 0 if complainant == "Tamana"
replace gender_dummy = 0 if complainant == "Tamana"
replace gender_dummy = 0 if complainant == "Tanjila"
replace gender_dummy = 0 if complainant == "Tanu"
replace gender_dummy = 0 if complainant == "Tanuja"
replace gender_dummy = 0 if complainant == "Tapi"
replace gender_dummy = 0 if complainant == "Tapshi"
replace gender_dummy = 0 if complainant == "Tapsi"
replace gender_dummy = 0 if complainant == "Tina"
replace gender_dummy = 0 if complainant == "Umrauti"
replace gender_dummy = 0 if complainant == "Umrawatyi"
replace gender_dummy = 0 if complainant == "Vibhuti"
replace gender_dummy = 0 if complainant == "Vidha"
replace gender_dummy = 0 if complainant == "Vina"
replace gender_dummy = 0 if complainant == "Vindavali"
replace gender_dummy = 0 if complainant == "Samundari"
replace gender_dummy = 0 if complainant == "Samiya"
replace gender_dummy = 0 if complainant == "Sakiya"
replace gender_dummy = 0 if complainant == "Sajara"
replace gender_dummy = 0 if complainant == "Umara"
replace gender_dummy = 0 if complainant == "Jwala"
replace gender_dummy = 0 if complainant == "Kalyani"
replace gender_dummy = 0 if complainant == "Giddi"
replace gender_dummy = 0 if complainant == "Yasmeen"
replace gender_dummy = 0 if complainant == "Tuntun"
replace gender_dummy = 0 if complainant == "Ruby"
replace gender_dummy = 0 if complainant == "Elijabeth"
replace gender_dummy = 0 if complainant == "Chhabila"
replace gender_dummy = 0 if complainant == "Aaesa"
replace gender_dummy = 0 if complainant == "Aaisa"
replace gender_dummy = 0 if complainant == "Aamba"
replace gender_dummy = 0 if complainant == "Aamna"
replace gender_dummy = 0 if complainant == "Aeshwari"
replace gender_dummy = 0 if complainant == "Akanchha"
replace gender_dummy = 0 if complainant == "Alesa"
replace gender_dummy = 0 if complainant == "Ambeya"
replace gender_dummy = 0 if complainant == "Amna"
replace gender_dummy = 0 if complainant == "Amveya"
replace gender_dummy = 0 if complainant == "Anchla"
replace gender_dummy = 0 if complainant == "Anichha"
replace gender_dummy = 0 if complainant == "Anihiya"
replace gender_dummy = 0 if complainant == "Babaita"
replace gender_dummy = 0 if complainant == "Bachchi"
replace gender_dummy = 0 if complainant == "Bachiya"
replace gender_dummy = 0 if complainant == "Balkeshwari"
replace gender_dummy = 0 if complainant == "Bibi"
replace gender_dummy = 0 if complainant == "Binti"
replace gender_dummy = 0 if complainant == "Champayi"
replace gender_dummy = 0 if complainant == "Chandabati"
replace gender_dummy = 0 if complainant == "Dhanesari"
replace gender_dummy = 0 if complainant == "Dona"
replace gender_dummy = 0 if complainant == "Draupadi"
replace gender_dummy = 0 if complainant == "Fulbhari"
replace gender_dummy = 0 if complainant == "Gamli"
replace gender_dummy = 0 if complainant == "Gautami"
replace gender_dummy = 0 if complainant == "Ghughuli"
replace gender_dummy = 0 if complainant == "Girija"
replace gender_dummy = 0 if complainant == "Godabari"
replace gender_dummy = 0 if complainant == "Godavari"
replace gender_dummy = 0 if complainant == "Gudli"
replace gender_dummy = 0 if complainant == "Gulabo"
replace gender_dummy = 0 if complainant == "Gulemra"
replace gender_dummy = 0 if complainant == "Guljara"
replace gender_dummy = 0 if complainant == "Guljarai"
replace gender_dummy = 0 if complainant == "Guljari"
replace gender_dummy = 0 if complainant == "Guri"
replace gender_dummy = 0 if complainant == "Ishwari"
replace gender_dummy = 0 if complainant == "Iswari"
replace gender_dummy = 0 if complainant == "Janila"
replace gender_dummy = 0 if complainant == "Jaysree"
replace gender_dummy = 0 if complainant == "Jaysri"
replace gender_dummy = 0 if complainant == "Jugti"
replace gender_dummy = 0 if complainant == "Jumni"
replace gender_dummy = 0 if complainant == "Kamali"
replace gender_dummy = 0 if complainant == "Kausaleya"
replace gender_dummy = 0 if complainant == "Kaushilya"
replace gender_dummy = 0 if complainant == "Kaushlya"
replace gender_dummy = 0 if complainant == "Khodeja"
replace gender_dummy = 0 if complainant == "Laita"
replace gender_dummy = 0 if complainant == "Lajo"
replace gender_dummy = 0 if complainant == "Laljhari"
replace gender_dummy = 0 if complainant == "Lalki"
replace gender_dummy = 0 if complainant == "Lalta"
replace gender_dummy = 0 if complainant == "Latita"
replace gender_dummy = 0 if complainant == "Madhwi"
replace gender_dummy = 0 if complainant == "Maduri"
replace gender_dummy = 0 if complainant == "Manaki"
replace gender_dummy = 0 if complainant == "Mandakani"
replace gender_dummy = 0 if complainant == "Manira"
replace gender_dummy = 0 if complainant == "Mansa"
replace gender_dummy = 0 if complainant == "Rahi"
replace gender_dummy = 0 if complainant == "Rosni"
replace gender_dummy = 0 if complainant == "Ruheli"
replace gender_dummy = 0 if complainant == "Rumali"
replace gender_dummy = 0 if complainant == "Saira"
replace gender_dummy = 0 if complainant == "Salmu"
replace gender_dummy = 0 if complainant == "Sanjhari"
replace gender_dummy = 0 if complainant == "Sanjya"
replace gender_dummy = 0 if complainant == "Shaira"
replace gender_dummy = 0 if complainant == "Shakiba"
replace gender_dummy = 0 if complainant == "Shandha"
replace gender_dummy = 0 if complainant == "Shayama"
replace gender_dummy = 0 if complainant == "Shushula"
replace gender_dummy = 0 if complainant == "Subhi"
replace gender_dummy = 0 if complainant == "Tahra"
replace gender_dummy = 0 if complainant == "Taira"
replace gender_dummy = 0 if complainant == "Taniyo"
replace gender_dummy = 0 if complainant == "Tulasi"
replace gender_dummy = 0 if complainant == "Ummrabati"
replace gender_dummy = 0 if complainant == "Amirka"
replace gender_dummy = 0 if complainant == "America"
replace gender_dummy = 0 if complainant == "Amreca"
replace gender_dummy = 0 if complainant == "Asin"
replace gender_dummy = 0 if complainant == "Baby"
replace gender_dummy = 0 if complainant == "Bebi"
replace gender_dummy = 0 if complainant == "Beby"
replace gender_dummy = 0 if complainant == "Subhadra"
replace gender_dummy = 0 if complainant == "Shobhi"
replace gender_dummy = 0 if complainant == "Shona"
replace gender_dummy = 0 if complainant == "Shnti"
replace gender_dummy = 0 if complainant == "Shbha"
replace gender_dummy = 0 if complainant == "Shamma"
replace gender_dummy = 0 if complainant == "Sasheila"
replace gender_dummy = 0 if complainant == "Rupmani"
replace gender_dummy = 0 if complainant == "Rukmani"
replace gender_dummy = 0 if complainant == "Rukmani"
replace gender_dummy = 0 if complainant == "Rukhamani"
replace gender_dummy = 0 if complainant == "Roja"
replace gender_dummy = 0 if complainant == "Rani"
replace gender_dummy = 0 if complainant == "Rangila"
replace gender_dummy = 0 if complainant == "Ramani"
replace gender_dummy = 0 if complainant == "Rajmani"
replace gender_dummy = 0 if complainant == "Praunka"
replace gender_dummy = 0 if complainant == "Nagmani"
replace gender_dummy = 0 if complainant == "Nanhi"
replace gender_dummy = 0 if complainant == "Nilmani"
replace gender_dummy = 0 if complainant == "Nilu"
replace gender_dummy = 0 if complainant == "Lila"
replace gender_dummy = 0 if complainant == "Liela"
replace gender_dummy = 0 if complainant == "Lela"
replace gender_dummy = 0 if complainant == "Lavangi"
replace gender_dummy = 0 if complainant == "Lalbati"
replace gender_dummy = 0 if complainant == "Krisnawatti"
replace gender_dummy = 0 if complainant == "Krishnawti"
replace gender_dummy = 0 if complainant == "Kishori"
replace gender_dummy = 0 if complainant == "Kanija"
replace gender_dummy = 0 if complainant == "Kamlawti"
replace gender_dummy = 0 if complainant == "Kalawti"
replace gender_dummy = 0 if complainant == "Janki"
replace gender_dummy = 0 if complainant == "Jalbhari"
replace gender_dummy = 0 if complainant == "Jaiyda"
replace gender_dummy = 0 if complainant == "Jabunesa"
replace gender_dummy = 0 if complainant == "Gauhami"
replace gender_dummy = 0 if complainant == "Fulpari"
replace gender_dummy = 0 if complainant == "Chandrawatti"
replace gender_dummy = 0 if complainant == "Chandramani"
replace gender_dummy = 0 if complainant == "Chandermani"
replace gender_dummy = 0 if complainant == "Bidhawti"
replace gender_dummy = 0 if complainant == "Bibhuti"
replace gender_dummy = 0 if complainant == "Bhagyamani"
replace gender_dummy = 0 if complainant == "Bhagmani"
replace gender_dummy = 0 if complainant == "Bhabhuti"
replace gender_dummy = 0 if complainant == "Bachhiya"
replace gender_dummy = 0 if complainant == "Bachchni"
replace gender_dummy = 0 if complainant == "Bachchiya"
replace gender_dummy = 0 if complainant == "Bacchi"
replace gender_dummy = 0 if complainant == "Baccchi"
replace gender_dummy = 0 if complainant == "Ashwini"
replace gender_dummy = 0 if complainant == "Ashmani"
replace gender_dummy = 0 if complainant == "Ashamani"
replace gender_dummy = 0 if complainant == "Aseya"
replace gender_dummy = 0 if complainant == "Arpita"
replace gender_dummy = 0 if complainant == "Anupma"
replace gender_dummy = 0 if complainant == "Anupama"
replace gender_dummy = 0 if complainant == "Anupma"
replace gender_dummy = 0 if complainant == "Amrica"
replace gender_dummy = 0 if complainant == "Amirca"
replace gender_dummy = 0 if complainant == "Amiraca"
replace gender_dummy = 0 if complainant == "Ambu"
replace gender_dummy = 0 if complainant == "Alaisa"
replace gender_dummy = 0 if complainant == "Aabha" 
replace gender_dummy = 0 if complainant == "Asna"
replace gender_dummy = 0 if complainant == "Aalta"
replace gender_dummy = 0 if complainant == "Aanandi"
replace gender_dummy = 0 if complainant == "Aarya"
replace gender_dummy = 0 if complainant == "Abhaya"
replace gender_dummy = 0 if complainant == "Aditi"
replace gender_dummy = 0 if complainant == "Alkha"
replace gender_dummy = 0 if complainant == "Amba"
replace gender_dummy = 0 if complainant == "Ambi"
replace gender_dummy = 0 if complainant == "Amibka"
replace gender_dummy = 0 if complainant == "Amta"
replace gender_dummy = 0 if complainant == "Amta"
replace gender_dummy = 0 if complainant == "Ansuiyaa"
replace gender_dummy = 0 if complainant == "Anupa"
replace gender_dummy = 0 if complainant == "Aprajita"
replace gender_dummy = 0 if complainant == "Ashvini"
replace gender_dummy = 0 if complainant == "Avnishi"
replace gender_dummy = 0 if complainant == "Bhajyamani"
replace gender_dummy = 0 if complainant == "Bindo"
replace gender_dummy = 0 if complainant == "Binu"
replace gender_dummy = 0 if complainant == "Buchhi"
replace gender_dummy = 0 if complainant == "Champha"
replace gender_dummy = 0 if complainant == "Chanadramani"
replace gender_dummy = 0 if complainant == "Chandrakala"
replace gender_dummy = 0 if complainant == "Chintamani"
replace gender_dummy = 0 if complainant == "Dhaneshwari"
replace gender_dummy = 0 if complainant == "Dhanoo"
replace gender_dummy = 0 if complainant == "Druga"
replace gender_dummy = 0 if complainant == "Duleshwari"
replace gender_dummy = 0 if complainant == "Duraga"
replace gender_dummy = 0 if complainant == "Durgabati"
replace gender_dummy = 0 if complainant == "Ekta"
replace gender_dummy = 0 if complainant == "Faguni"
replace gender_dummy = 0 if complainant == "Gajandhari"
replace gender_dummy = 0 if complainant == "Gangotri"
replace gender_dummy = 0 if complainant == "Gudi"
replace gender_dummy = 0 if complainant == "Gunjeswari"
replace gender_dummy = 0 if complainant == "Indrasani"
replace gender_dummy = 0 if complainant == "Indushewari"
replace gender_dummy = 0 if complainant == "Jaiki"
replace gender_dummy = 0 if complainant == "Jhaleshwari"
replace gender_dummy = 0 if complainant == "Jhunari"
replace gender_dummy = 0 if complainant == "Jitni"
replace gender_dummy = 0 if complainant == "Kalayani"
replace gender_dummy = 0 if complainant == "Kamakheaya"
replace gender_dummy = 0 if complainant == "Kamakhya"
replace gender_dummy = 0 if complainant == "Kamekhya"
replace gender_dummy = 0 if complainant == "Kameshwari"
replace gender_dummy = 0 if complainant == "Kamkhya"
replace gender_dummy = 0 if complainant == "Kamli"
replace gender_dummy = 0 if complainant == "Kamrubha"
replace gender_dummy = 0 if complainant == "Keshjhari"
replace gender_dummy = 0 if complainant == "Khalifa"
replace gender_dummy = 0 if complainant == "Khamakhya"
replace gender_dummy = 0 if complainant == "Khamkhya"
replace gender_dummy = 0 if complainant == "Khusi"
replace gender_dummy = 0 if complainant == "Krishanbati"
replace gender_dummy = 0 if complainant == "Kulbadni"
replace gender_dummy = 0 if complainant == "Kusela"
replace gender_dummy = 0 if complainant == "Kusumi"
replace gender_dummy = 0 if complainant == "Laalsa"
replace gender_dummy = 0 if complainant == "Lachhiya"
replace gender_dummy = 0 if complainant == "Lachiya"
replace gender_dummy = 0 if complainant == "Lacho"
replace gender_dummy = 0 if complainant == "Laksjmi"
replace gender_dummy = 0 if complainant == "Lalo"
replace gender_dummy = 0 if complainant == "Lalsa"
replace gender_dummy = 0 if complainant == "Lalsha"
replace gender_dummy = 0 if complainant == "Lili"
replace gender_dummy = 0 if complainant == "Lipi"
replace gender_dummy = 0 if complainant == "Luci"
replace gender_dummy = 0 if complainant == "Maheshvari"
replace gender_dummy = 0 if complainant == "Maheshwari"
replace gender_dummy = 0 if complainant == "Maheswari"
replace gender_dummy = 0 if complainant == "Maheswari"
replace gender_dummy = 0 if complainant == "Manjhari"
replace gender_dummy = 0 if complainant == "Minashki"
replace gender_dummy = 0 if complainant == "Mita"
replace gender_dummy = 0 if complainant == "Namrata"
replace gender_dummy = 0 if complainant == "Nausaba"
replace gender_dummy = 0 if complainant == "Neshi"
replace gender_dummy = 0 if complainant == "Nickki"
replace gender_dummy = 0 if complainant == "Nima"
replace gender_dummy = 0 if complainant == "Nimiya"
replace gender_dummy = 0 if complainant == "Nimu"
replace gender_dummy = 0 if complainant == "Nitoo"
replace gender_dummy = 0 if complainant == "Nshu"
replace gender_dummy = 0 if complainant == "Nudhi"
replace gender_dummy = 0 if complainant == "Nuraisa"
replace gender_dummy = 0 if complainant == "Nuri"
replace gender_dummy = 0 if complainant == "Pami"
replace gender_dummy = 0 if complainant == "Pampi"
replace gender_dummy = 0 if complainant == "Parbati"
replace gender_dummy = 0 if complainant == "Paro"
replace gender_dummy = 0 if complainant == "Parvila"
replace gender_dummy = 0 if complainant == "Parwatti"
replace gender_dummy = 0 if complainant == "Phagoo"
replace gender_dummy = 0 if complainant == "Phagu"
replace gender_dummy = 0 if complainant == "Phaguni"
replace gender_dummy = 0 if complainant == "Pharidha"
replace gender_dummy = 0 if complainant == "Phatama"
replace gender_dummy = 0 if complainant == "Phooleshwari"
replace gender_dummy = 0 if complainant == "Phoolwari"
replace gender_dummy = 0 if complainant == "Phuleshwari"
replace gender_dummy = 0 if complainant == "Phulwaro"
replace gender_dummy = 0 if complainant == "Prabhabati"
replace gender_dummy = 0 if complainant == "Premta"
replace gender_dummy = 0 if complainant == "Priyanaka"
replace gender_dummy = 0 if complainant == "Priyansu"
replace gender_dummy = 0 if complainant == "Pushpanjai"
replace gender_dummy = 0 if complainant == "Pushpha"
replace gender_dummy = 0 if complainant == "Rabhya"
replace gender_dummy = 0 if complainant == "Rabia"
replace gender_dummy = 0 if complainant == "Radika"
replace gender_dummy = 0 if complainant == "Rafika"
replace gender_dummy = 0 if complainant == "Rajeshwari"
replace gender_dummy = 0 if complainant == "Rajeya"
replace gender_dummy = 0 if complainant == "Rajkeshwari"
replace gender_dummy = 0 if complainant == "Ramabati"
replace gender_dummy = 0 if complainant == "Rameshwari"
replace gender_dummy = 0 if complainant == "Ramyela"
replace gender_dummy = 0 if complainant == "Roya"
replace gender_dummy = 0 if complainant == "Rukiya"
replace gender_dummy = 0 if complainant == "Sabia"
replace gender_dummy = 0 if complainant == "Salauni"
replace gender_dummy = 0 if complainant == "Sarayu"
replace gender_dummy = 0 if complainant == "Sarifa"
replace gender_dummy = 0 if complainant == "Saryu"
replace gender_dummy = 0 if complainant == "Sati"
replace gender_dummy = 0 if complainant == "Savitree"
replace gender_dummy = 0 if complainant == "Sayeda"
replace gender_dummy = 0 if complainant == "Shailja"
replace gender_dummy = 0 if complainant == "Shawpna"
replace gender_dummy = 0 if complainant == "Shewta"
replace gender_dummy = 0 if complainant == "Shreya"
replace gender_dummy = 0 if complainant == "Shre"
replace gender_dummy = 0 if complainant == "Shyama"
replace gender_dummy = 0 if complainant == "Simta"
replace gender_dummy = 0 if complainant == "Sonajhari"
replace gender_dummy = 0 if complainant == "Sonjhari"
replace gender_dummy = 0 if complainant == "Sonjharo"
replace gender_dummy = 0 if complainant == "Suanina"
replace gender_dummy = 0 if complainant == "Subha"
replace gender_dummy = 0 if complainant == "Subhagiya"
replace gender_dummy = 0 if complainant == "Subhago"
replace gender_dummy = 0 if complainant == "Sugandha"
replace gender_dummy = 0 if complainant == "Sugandhi"
replace gender_dummy = 0 if complainant == "Sumi"
replace gender_dummy = 0 if complainant == "Summi"
replace gender_dummy = 0 if complainant == "Suwiti"
replace gender_dummy = 0 if complainant == "Susma"
replace gender_dummy = 0 if complainant == "Syama"
replace gender_dummy = 0 if complainant == "Tabbu"
replace gender_dummy = 0 if complainant == "Taiba"
replace gender_dummy = 0 if complainant == "Tana"
replace gender_dummy = 0 if complainant == "Tanaya"
replace gender_dummy = 0 if complainant == "Tapasya"
replace gender_dummy = 0 if complainant == "Tapesari"
replace gender_dummy = 0 if complainant == "Tapeshwari"
replace gender_dummy = 0 if complainant == "Tavishi"
replace gender_dummy = 0 if complainant == "Tileshvari"
replace gender_dummy = 0 if complainant == "Vida"
replace gender_dummy = 0 if complainant == "Vindeshwari"
replace gender_dummy = 0 if complainant == "Vindha"
replace gender_dummy = 0 if complainant == "Vineswari"
replace gender_dummy = 0 if complainant == "Vrinda"
replace gender_dummy = 0 if complainant == "Yamunna"
replace gender_dummy = 0 if complainant == "Aadya"
replace gender_dummy = 0 if complainant == "Aakriki"
replace gender_dummy = 0 if complainant == "Aalaha"
replace gender_dummy = 0 if complainant == "Aalha"
replace gender_dummy = 0 if complainant == "Aanandee"
replace gender_dummy = 0 if complainant == "Aani"
replace gender_dummy = 0 if complainant == "Aaratee"
replace gender_dummy = 0 if complainant == "Aashara"
replace gender_dummy = 0 if complainant == "Aashiya"
replace gender_dummy = 0 if complainant == "Abeya"
replace gender_dummy = 0 if complainant == "Afira"
replace gender_dummy = 0 if complainant == "Akshra"
replace gender_dummy = 0 if complainant == "Ama"
replace gender_dummy = 0 if complainant == "Anarkalee"
replace gender_dummy = 0 if complainant == "Anganu"
replace gender_dummy = 0 if complainant == "Aniita"
replace gender_dummy = 0 if complainant == "Anipa"
replace gender_dummy = 0 if complainant == "Anjnee"
replace gender_dummy = 0 if complainant == "Anjni"
replace gender_dummy = 0 if complainant == "Anuja"
replace gender_dummy = 0 if complainant == "Anya"
replace gender_dummy = 0 if complainant == "Ashya"
replace gender_dummy = 0 if complainant == "Ashwinee"
replace gender_dummy = 0 if complainant == "Ashwineee"
replace gender_dummy = 0 if complainant == "Asiwni"
replace gender_dummy = 0 if complainant == "Aswini"
replace gender_dummy = 0 if complainant == "Bachchee"
replace gender_dummy = 0 if complainant == "Bageshwari"
replace gender_dummy = 0 if complainant == "Basantee"
replace gender_dummy = 0 if complainant == "Bbli"
replace gender_dummy = 0 if complainant == "Babli"
replace gender_dummy = 0 if complainant == "Bhagamanee"
replace gender_dummy = 0 if complainant == "Bhagamani"
replace gender_dummy = 0 if complainant == "Bhagmanee"
replace gender_dummy = 0 if complainant == "Bhagmano"
replace gender_dummy = 0 if complainant == "Bhairvee"
replace gender_dummy = 0 if complainant == "Bhuwali"
replace gender_dummy = 0 if complainant == "Bidu"
replace gender_dummy = 0 if complainant == "Bijalee"
replace gender_dummy = 0 if complainant == "Bndu"
replace gender_dummy = 0 if complainant == "Bindu"
replace gender_dummy = 0 if complainant == "Brinda"
replace gender_dummy = 0 if complainant == "Buchchee"
replace gender_dummy = 0 if complainant == "Buchchi"
replace gender_dummy = 0 if complainant == "Buchee"
replace gender_dummy = 0 if complainant == "Buchiya"
replace gender_dummy = 0 if complainant == "Chadarwti"
replace gender_dummy = 0 if complainant == "Chandamani"
replace gender_dummy = 0 if complainant == "Chandanee"
replace gender_dummy = 0 if complainant == "Chandmatee"
replace gender_dummy = 0 if complainant == "Chandmatia"
replace gender_dummy = 0 if complainant == "Chandrawatee"
replace gender_dummy = 0 if complainant == "Chandrica"
replace gender_dummy = 0 if complainant == "Chavila"
replace gender_dummy = 0 if complainant == "Chunee"
replace gender_dummy = 0 if complainant == "Devkee"
replace gender_dummy = 0 if complainant == "Dhaneshwaree"
replace gender_dummy = 0 if complainant == "Dhanmatee"
replace gender_dummy = 0 if complainant == "Dhanmatiya"
replace gender_dummy = 0 if complainant == "Dharmawatee"
replace gender_dummy = 0 if complainant == "Dhnavti"
replace gender_dummy = 0 if complainant == "Diya"
replace gender_dummy = 0 if complainant == "Diwa"
replace gender_dummy = 0 if complainant == "Dugeshi"
replace gender_dummy = 0 if complainant == "Durgawatee"
replace gender_dummy = 0 if complainant == "Endarwti"
replace gender_dummy = 0 if complainant == "Endavti"
replace gender_dummy = 0 if complainant == "Endawadi"
replace gender_dummy = 0 if complainant == "Esa"
replace gender_dummy = 0 if complainant == "Esha"
replace gender_dummy = 0 if complainant == "Fagu"
replace gender_dummy = 0 if complainant == "Fatama"
replace gender_dummy = 0 if complainant == "Fatima"
replace gender_dummy = 0 if complainant == "Feeroja"
replace gender_dummy = 0 if complainant == "Fulmatee"
replace gender_dummy = 0 if complainant == "Gaetri"
replace gender_dummy = 0 if complainant == "Gaga"
replace gender_dummy = 0 if complainant == "Gautmi"
replace gender_dummy = 0 if complainant == "Gayatree"
replace gender_dummy = 0 if complainant == "Gaytree"
replace gender_dummy = 0 if complainant == "Gudhi"
replace gender_dummy = 0 if complainant == "Gudhiya"
replace gender_dummy = 0 if complainant == "Hadya"
replace gender_dummy = 0 if complainant == "Indrabalee"
replace gender_dummy = 0 if complainant == "Indrawatee"
replace gender_dummy = 0 if complainant == "Jahnara"
replace gender_dummy = 0 if complainant == "Jaynara"
replace gender_dummy = 0 if complainant == "Jhapasee"
replace gender_dummy = 0 if complainant == "Jhapshi"
replace gender_dummy = 0 if complainant == "Jigyasa"
replace gender_dummy = 0 if complainant == "Jubaidha"
replace gender_dummy = 0 if complainant == "Jyati"
replace gender_dummy = 0 if complainant == "Jyotee"
replace gender_dummy = 0 if complainant == "Kamalawatee"
replace gender_dummy = 0 if complainant == "Karishiama"
replace gender_dummy = 0 if complainant == "Kaushalaya"
replace gender_dummy = 0 if complainant == "Kaushalee"
replace gender_dummy = 0 if complainant == "Kaushlaya"
replace gender_dummy = 0 if complainant == "Khadija"
replace gender_dummy = 0 if complainant == "Khalipha"
replace gender_dummy = 0 if complainant == "Kisanawatee"
replace gender_dummy = 0 if complainant == "Kisnawti"
replace gender_dummy = 0 if complainant == "Krishnawatee"
replace gender_dummy = 0 if complainant == "Kumaree"
replace gender_dummy = 0 if complainant == "Kushmawti"
replace gender_dummy = 0 if complainant == "Kusnawti"
replace gender_dummy = 0 if complainant == "Kusumkala"
replace gender_dummy = 0 if complainant == "Ladalee"
replace gender_dummy = 0 if complainant == "Lakshmee"
replace gender_dummy = 0 if complainant == "Laksmi"
replace gender_dummy = 0 if complainant == "Leelawatee"
replace gender_dummy = 0 if complainant == "Lilawatee"
replace gender_dummy = 0 if complainant == "Mahi"
replace gender_dummy = 0 if complainant == "Mandodaree"
replace gender_dummy = 0 if complainant == "Majhari"
replace gender_dummy = 0 if complainant == "Malthi"
replace gender_dummy = 0 if complainant == "Manakee"
replace gender_dummy = 0 if complainant == "Mateshwari"
replace gender_dummy = 0 if complainant == "Mithi"
replace gender_dummy = 0 if complainant == "Mayapti"
replace gender_dummy = 0 if complainant == "Miki"
replace gender_dummy = 0 if complainant == "Mini"
replace gender_dummy = 0 if complainant == "Mnju"
replace gender_dummy = 0 if complainant == "Nagamani"
replace gender_dummy = 0 if complainant == "Nagmanee"
replace gender_dummy = 0 if complainant == "Noorsaba"
replace gender_dummy = 0 if complainant == "Nursaba"
replace gender_dummy = 0 if complainant == "Nurshwa"
replace gender_dummy = 0 if complainant == "Nurswa"
replace gender_dummy = 0 if complainant == "Pabhawti"
replace gender_dummy = 0 if complainant == "Padmi"
replace gender_dummy = 0 if complainant == "Pallawee"
replace gender_dummy = 0 if complainant == "Pallvee"
replace gender_dummy = 0 if complainant == "Parbhawti"
replace gender_dummy = 0 if complainant == "Pargavti"
replace gender_dummy = 0 if complainant == "Partigya"
replace gender_dummy = 0 if complainant == "Parvatee"
replace gender_dummy = 0 if complainant == "Parvathi"
replace gender_dummy = 0 if complainant == "Parwatee"
replace gender_dummy = 0 if complainant == "Pavithri"
replace gender_dummy = 0 if complainant == "Pavtree"
replace gender_dummy = 0 if complainant == "Phuljharee"
replace gender_dummy = 0 if complainant == "Phulkalee"
replace gender_dummy = 0 if complainant == "Phulkishoree"
replace gender_dummy = 0 if complainant == "Phulkumaree"
replace gender_dummy = 0 if complainant == "Phulmatee"
replace gender_dummy = 0 if complainant == "Pirya"
replace gender_dummy = 0 if complainant == "Piya"
replace gender_dummy = 0 if complainant == "Prabha"
replace gender_dummy = 0 if complainant == "Prabhawatee"
replace gender_dummy = 0 if complainant == "Pranchee"
replace gender_dummy = 0 if complainant == "Preetee"
replace gender_dummy = 0 if complainant == "Priye"
replace gender_dummy = 0 if complainant == "Purnavasi"
replace gender_dummy = 0 if complainant == "Purnwasi"
replace gender_dummy = 0 if complainant == "Pushpanjalee"
replace gender_dummy = 0 if complainant == "Rabaiya"
replace gender_dummy = 0 if complainant == "Rabbeya"
replace gender_dummy = 0 if complainant == "Rabija"
replace gender_dummy = 0 if complainant == "Raisanee"
replace gender_dummy = 0 if complainant == "Rajlakshmee"
replace gender_dummy = 0 if complainant == "Rajo"
replace gender_dummy = 0 if complainant == "Rajsri"
replace gender_dummy = 0 if complainant == "Rajya"
replace gender_dummy = 0 if complainant == "Ramavti"
replace gender_dummy = 0 if complainant == "Ramawatee"
replace gender_dummy = 0 if complainant == "Ramkumaree"
replace gender_dummy = 0 if complainant == "Rbri"
replace gender_dummy = 0 if complainant == "Rimpa"
replace gender_dummy = 0 if complainant == "Riti"
replace gender_dummy = 0 if complainant == "Ruhee"
replace gender_dummy = 0 if complainant == "Rukamanee"
replace gender_dummy = 0 if complainant == "Rukamatee"
replace gender_dummy = 0 if complainant == "Rukhminee"
replace gender_dummy = 0 if complainant == "Rumalee"
replace gender_dummy = 0 if complainant == "Rumi"
replace gender_dummy = 0 if complainant == "Runna"
replace gender_dummy = 0 if complainant == "Rupi"
replace gender_dummy = 0 if complainant == "Rupjharee"
replace gender_dummy = 0 if complainant == "Rupjhari"
replace gender_dummy = 0 if complainant == "Rushiya"
replace gender_dummy = 0 if complainant == "Saameya"
replace gender_dummy = 0 if complainant == "Sabaya"
replace gender_dummy = 0 if complainant == "Sabeeha"
replace gender_dummy = 0 if complainant == "Sabeetri"
replace gender_dummy = 0 if complainant == "Sabha"
replace gender_dummy = 0 if complainant == "Sadhiya"
replace gender_dummy = 0 if complainant == "Sadya"
replace gender_dummy = 0 if complainant == "Sahelee"
replace gender_dummy = 0 if complainant == "Sajira"
replace gender_dummy = 0 if complainant == "Sakunthala"
replace gender_dummy = 0 if complainant == "Saleeha"
replace gender_dummy = 0 if complainant == "Salehra"
replace gender_dummy = 0 if complainant == "Salonee"
replace gender_dummy = 0 if complainant == "Samlavatee"
replace gender_dummy = 0 if complainant == "Samlawti"
replace gender_dummy = 0 if complainant == "Sampti"
replace gender_dummy = 0 if complainant == "Sanhaywti"
replace gender_dummy = 0 if complainant == "Sanjidha"
replace gender_dummy = 0 if complainant == "Saphi"
replace gender_dummy = 0 if complainant == "Saralee"
replace gender_dummy = 0 if complainant == "Sarsati"
replace gender_dummy = 0 if complainant == "Sarsti"
replace gender_dummy = 0 if complainant == "Sarswatee"
replace gender_dummy = 0 if complainant == "Satee"
replace gender_dummy = 0 if complainant == "Sateebha"
replace gender_dummy = 0 if complainant == "Savithri"
replace gender_dummy = 0 if complainant == "Savtree"
replace gender_dummy = 0 if complainant == "Sayama"
replace gender_dummy = 0 if complainant == "Sayamda"
replace gender_dummy = 0 if complainant == "Shabanee"
replace gender_dummy = 0 if complainant == "Shabbu"
replace gender_dummy = 0 if complainant == "Shabha"
replace gender_dummy = 0 if complainant == "Shakunthla"
replace gender_dummy = 0 if complainant == "Shalni"
replace gender_dummy = 0 if complainant == "Shantee"
replace gender_dummy = 0 if complainant == "Shayda"
replace gender_dummy = 0 if complainant == "Shilpee"
replace gender_dummy = 0 if complainant == "Shubhadra"
replace gender_dummy = 0 if complainant == "Shubhavti"
replace gender_dummy = 0 if complainant == "Shubhawti"
replace gender_dummy = 0 if complainant == "Shugandhiya"
replace gender_dummy = 0 if complainant == "Simi"
replace gender_dummy = 0 if complainant == "Sonamatee"
replace gender_dummy = 0 if complainant == "Sonamato"
replace gender_dummy = 0 if complainant == "Sreejawti"
replace gender_dummy = 0 if complainant == "Sreematee"
replace gender_dummy = 0 if complainant == "Srimatee"
replace gender_dummy = 0 if complainant == "Subhalati"
replace gender_dummy = 0 if complainant == "Subhasni"
replace gender_dummy = 0 if complainant == "Subhavti"
replace gender_dummy = 0 if complainant == "Subhawatee"
replace gender_dummy = 0 if complainant == "Subhnti"
replace gender_dummy = 0 if complainant == "Sujawatee"
replace gender_dummy = 0 if complainant == "Sulawatee"
replace gender_dummy = 0 if complainant == "Sumalati"
replace gender_dummy = 0 if complainant == "Sumalatee"
replace gender_dummy = 0 if complainant == "Sumalawatee"
replace gender_dummy = 0 if complainant == "Sumatati"
replace gender_dummy = 0 if complainant == "Surabhee"
replace gender_dummy = 0 if complainant == "Surasatee"
replace gender_dummy = 0 if complainant == "Sursatiya"
replace gender_dummy = 0 if complainant == "Sursti"
replace gender_dummy = 0 if complainant == "Surswatee"
replace gender_dummy = 0 if complainant == "Taea"
replace gender_dummy = 0 if complainant == "Tileshwaree"
replace gender_dummy = 0 if complainant == "Tileshwari"
replace gender_dummy = 0 if complainant == "Uamarawatee"
replace gender_dummy = 0 if complainant == "Ujwala"
replace gender_dummy = 0 if complainant == "Umarawatee"
replace gender_dummy = 0 if complainant == "Vashantee"
replace gender_dummy = 0 if complainant == "Vibhamani"
replace gender_dummy = 0 if complainant == "Vibhawatee"
replace gender_dummy = 0 if complainant == "Vidawatee"
replace gender_dummy = 0 if complainant == "Vidhawatee"
replace gender_dummy = 0 if complainant == "Vidhawti"
replace gender_dummy = 0 if complainant == "Vidyawatee"
replace gender_dummy = 0 if complainant == "Vimalawatee"
replace gender_dummy = 0 if complainant == "Viondha"

replace gender_dummy = 1 if complainant == "Abdesh"
replace gender_dummy = 1 if complainant == "Ahilesh"
replace gender_dummy = 1 if complainant == "Ahilesh"
replace gender_dummy = 1 if complainant == "Akhilesh"
replace gender_dummy = 1 if complainant == "Akhlesh"
replace gender_dummy = 1 if complainant == "Alakhniranjan"
replace gender_dummy = 1 if complainant == "Amlesh"
replace gender_dummy = 1 if complainant == "Amlesh"
replace gender_dummy = 1 if complainant == "Anshuman"
replace gender_dummy = 1 if complainant == "Anwar"
replace gender_dummy = 1 if complainant == "Anwarul"
replace gender_dummy = 1 if complainant == "Ashutosh"
replace gender_dummy = 1 if complainant == "Avdesh"
replace gender_dummy = 1 if complainant == "Awadesh"
replace gender_dummy = 1 if complainant == "Haidar"
replace gender_dummy = 1 if complainant == "Imran"
replace gender_dummy = 1 if complainant == "Jahangir"
replace gender_dummy = 1 if complainant == "Kailesh"
replace gender_dummy = 1 if complainant == "Kamlesh"
replace gender_dummy = 1 if complainant == "Laxuman"
replace gender_dummy = 1 if complainant == "Lakshuman"
replace gender_dummy = 1 if complainant == "Lachhuman"
replace gender_dummy = 1 if complainant == "Lahkan"
replace gender_dummy = 1 if complainant == "Mithelesh"
replace gender_dummy = 1 if complainant == "Mithilesh"
replace gender_dummy = 1 if complainant == "Mithlesh"
replace gender_dummy = 1 if complainant == "Mitilesh"
replace gender_dummy = 1 if complainant == "Raghuwar"
replace gender_dummy = 1 if complainant == "Ramdayal"
replace gender_dummy = 1 if complainant == "Ramjanam"
replace gender_dummy = 1 if complainant == "Ramjit"
replace gender_dummy = 1 if complainant == "Rampukar"
replace gender_dummy = 1 if complainant == "Ramranjan"
replace gender_dummy = 1 if complainant == "Ramsubhag"
replace gender_dummy = 1 if complainant == "Ramwachan"
replace gender_dummy = 1 if complainant == "Raviranjan"
replace gender_dummy = 1 if complainant == "Sailesh"
replace gender_dummy = 1 if complainant == "Shailesh"
replace gender_dummy = 1 if complainant == "Shalesh"
replace gender_dummy = 1 if complainant == "Vikramjit"
replace gender_dummy = 1 if complainant == "Zunaid"
replace gender_dummy = 1 if complainant == "Ajarul"
replace gender_dummy = 1 if complainant == "Ajarul"
replace gender_dummy = 1 if complainant == "Akalesh"
replace gender_dummy = 1 if complainant == "Akwar"
replace gender_dummy = 1 if complainant == "Alhilesh"
replace gender_dummy = 1 if complainant == "Amalesh"
replace gender_dummy = 1 if complainant == "Anavarul"
replace gender_dummy = 1 if complainant == "Anawar"
replace gender_dummy = 1 if complainant == "Anbarul"
replace gender_dummy = 1 if complainant == "Ashitosh"
replace gender_dummy = 1 if complainant == "Asutosh"
replace gender_dummy = 1 if complainant == "Avadesh"
replace gender_dummy = 1 if complainant == "Awdesh"
replace gender_dummy = 1 if complainant == "Emran"
replace gender_dummy = 1 if complainant == "Firdos"
replace gender_dummy = 1 if complainant == "Firdosh"
replace gender_dummy = 1 if complainant == "Gurudayal"
replace gender_dummy = 1 if complainant == "Hanuman"
replace gender_dummy = 1 if complainant == "Herdayal"
replace gender_dummy = 1 if complainant == "Jaikishun"
replace gender_dummy = 1 if complainant == "Jaykishun"
replace gender_dummy = 1 if complainant == "Kamalesh"
replace gender_dummy = 1 if complainant == "Kamarul"
replace gender_dummy = 1 if complainant == "Kamran"
replace gender_dummy = 1 if complainant == "Lalkishun"
replace gender_dummy = 1 if complainant == "Lamlesh"
replace gender_dummy = 1 if complainant == "Mithalesh"
replace gender_dummy = 1 if complainant == "Navlesh"
replace gender_dummy = 1 if complainant == "Naveen"
replace gender_dummy = 1 if complainant == "Nilesh"
replace gender_dummy = 1 if complainant == "Rabiranjan"
replace gender_dummy = 1 if complainant == "Rambachan"
replace gender_dummy = 1 if complainant == "Rambachchan"
replace gender_dummy = 1 if complainant == "Rambalak"
replace gender_dummy = 1 if complainant == "Rambhulesh"
replace gender_dummy = 1 if complainant == "Ramlochan"
replace gender_dummy = 1 if complainant == "Rampat"
replace gender_dummy = 1 if complainant == "Ramtosh"
replace gender_dummy = 1 if complainant == "Ramudesh"
replace gender_dummy = 1 if complainant == "Ramvashist"
replace gender_dummy = 1 if complainant == "Sahjahan"
replace gender_dummy = 1 if complainant == "Sahjhan"
replace gender_dummy = 1 if complainant == "Santosh"
replace gender_dummy = 1 if complainant == "Shanjahan"
replace gender_dummy = 1 if complainant == "Shaislesh"
replace gender_dummy = 1 if complainant == "Shivbalak"
replace gender_dummy = 1 if complainant == "Shivdayal"
replace gender_dummy = 1 if complainant == "Shivlochan"
replace gender_dummy = 1 if complainant == "Sivranjan"
replace gender_dummy = 1 if complainant == "Snatosh"
replace gender_dummy = 1 if complainant == "Ujjaval"
replace gender_dummy = 1 if complainant == "Vazir"
replace gender_dummy = 1 if complainant == "Vimlesh"
replace gender_dummy = 1 if complainant == "Aashutosh"
replace gender_dummy = 1 if complainant == "Aasutosh"
replace gender_dummy = 1 if complainant == "Aikhalak"
replace gender_dummy = 1 if complainant == "Akhalesh"
replace gender_dummy = 1 if complainant == "Akilesh"
replace gender_dummy = 1 if complainant == "Aklesh"
replace gender_dummy = 1 if complainant == "Avilesh"
replace gender_dummy = 1 if complainant == "Avilesh"
replace gender_dummy = 1 if complainant == "Awlesh"
replace gender_dummy = 1 if complainant == "Chitaranjan"
replace gender_dummy = 1 if complainant == "Chitranjan"
replace gender_dummy = 1 if complainant == "Dipchan"
replace gender_dummy = 1 if complainant == "Jaychan"
replace gender_dummy = 1 if complainant == "Kameshawar"
replace gender_dummy = 1 if complainant == "Kamnlesh"
replace gender_dummy = 1 if complainant == "Lachuman"
replace gender_dummy = 1 if complainant == "Laxchuman"
replace gender_dummy = 1 if complainant == "Mangalesh"
replace gender_dummy = 1 if complainant == "Mitlesh"
replace gender_dummy = 1 if complainant == "Mo Imran"
replace gender_dummy = 1 if complainant == "Munawar"
replace gender_dummy = 1 if complainant == "Navin"
replace gender_dummy = 1 if complainant == "Nawalesh"
replace gender_dummy = 1 if complainant == "Nawlesh"
replace gender_dummy = 1 if complainant == "Niranjan"
replace gender_dummy = 1 if complainant == "Pjravin"
replace gender_dummy = 1 if complainant == "Ramauraon"
replace gender_dummy = 1 if complainant == "Ramawdesh"
replace gender_dummy = 1 if complainant == "Ramgeet"
replace gender_dummy = 1 if complainant == "Ramishar"
replace gender_dummy = 1 if complainant == "Ramishavar"
replace gender_dummy = 1 if complainant == "Ramjas"
replace gender_dummy = 1 if complainant == "Ramkesar"
replace gender_dummy = 1 if complainant == "Risabh"
replace gender_dummy = 1 if complainant == "Rituranjan"
replace gender_dummy = 1 if complainant == "Samsad"
replace gender_dummy = 1 if complainant == "Shahjahan"
replace gender_dummy = 1 if complainant == "Shahjhan"
replace gender_dummy = 1 if complainant == "Shivbachan"
replace gender_dummy = 1 if complainant == "Shivjanam"
replace gender_dummy = 1 if complainant == "Shivpukar"
replace gender_dummy = 1 if complainant == "Sivdayal"
replace gender_dummy = 1 if complainant == "Sjailesh"
replace gender_dummy = 1 if complainant == "Suryavansham"
replace gender_dummy = 1 if complainant == "Umlesh"
replace gender_dummy = 1 if complainant == "Vimalesh"
replace gender_dummy = 1 if complainant == "Vimelesh"
replace gender_dummy = 1 if complainant == "Aashotosh"
replace gender_dummy = 1 if complainant == "Aashotosh"
replace gender_dummy = 1 if complainant == "Arvin"
replace gender_dummy = 1 if complainant == "Ashotosh"
replace gender_dummy = 1 if complainant == "Atulesh"
replace gender_dummy = 1 if complainant == "Barjbhusham"
replace gender_dummy = 1 if complainant == "Gauraw"
replace gender_dummy = 1 if complainant == "Gulabchan"
replace gender_dummy = 1 if complainant == "Hardayal"
replace gender_dummy = 1 if complainant == "Kunwar"
replace gender_dummy = 1 if complainant == "Kuwar"
replace gender_dummy = 1 if complainant == "Lalchan"
replace gender_dummy = 1 if complainant == "Manauwar"
replace gender_dummy = 1 if complainant == "Manawar"
replace gender_dummy = 1 if complainant == "Manwar"
replace gender_dummy = 1 if complainant == "Matuwar"
replace gender_dummy = 1 if complainant == "Mithlish"
replace gender_dummy = 1 if complainant == "Muneshawar"
replace gender_dummy = 1 if complainant == "Paramhans"
replace gender_dummy = 1 if complainant == "Phulchan"
replace gender_dummy = 1 if complainant == "Prabhudayal"
replace gender_dummy = 1 if complainant == "Rajeevranjan"
replace gender_dummy = 1 if complainant == "Ramanjan"
replace gender_dummy = 1 if complainant == "Ramashis"
replace gender_dummy = 1 if complainant == "Ramjanak"
replace gender_dummy = 1 if complainant == "Ramkarn"
replace gender_dummy = 1 if complainant == "Ramkuwar"
replace gender_dummy = 1 if complainant == "Rampyar"
replace gender_dummy = 1 if complainant == "Ramvichar"
replace gender_dummy = 1 if complainant == "Sahilesh"
replace gender_dummy = 1 if complainant == "Sanauwar"
replace gender_dummy = 1 if complainant == "Satosh"
replace gender_dummy = 1 if complainant == "Shahajahan"
replace gender_dummy = 1 if complainant == "Shamsad"
replace gender_dummy = 1 if complainant == "Sheevlochan"
replace gender_dummy = 1 if complainant == "Shivbachchan"
replace gender_dummy = 1 if complainant == "Shiwachan"
replace gender_dummy = 1 if complainant == "Shiwbachan"
replace gender_dummy = 1 if complainant == "Sukeshawar"
replace gender_dummy = 1 if complainant == "Tiger"
replace gender_dummy = 1 if complainant == "Vishwas"

save "${intermediate_dta}Clean_Python\clean_gopalganj.dta", replace